services:
  # Flightlog Decoder
  flightlog-decoder:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/docker/build/flightlog-decoder/Dockerfile
    environment:
      - SDK_KEY=${DJI_SDK_KEY}
    platform: linux/amd64
    ports:
      - 8088:8080
    networks:
      - default
      - webgateway
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8080"]
      interval: 3s
      timeout: 3s
      retries: 10
    restart: always

networks:
  webgateway:
    external: true